# Generated by Django 2.2.4 on 2019-08-14 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '启用'), ('forbidden', '禁用')], max_length=20, verbose_name='状态')),
                ('product_type', models.CharField(choices=[('native', '国内'), ('abroad', '国外'), ('surround', '周边'), ('other', '其它'), ('mail_steamer', '邮轮')], max_length=10, verbose_name='产品类型')),
                ('en_name', models.CharField(max_length=200, verbose_name='英文')),
                ('type_name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('line_amount', models.IntegerField(verbose_name='线路数量')),
                ('contract_type', models.CharField(choices=[('native', '国内游'), ('abroad', '国外游'), ('one_day', '一日游'), ('Taiwan', '台湾游')], max_length=10, verbose_name='合同类型')),
                ('deduction_point', models.CharField(max_length=100, verbose_name='扣点')),
                ('weight', models.IntegerField(verbose_name='权重')),
                ('tag_info', models.CharField(max_length=50, verbose_name='标签信息')),
                ('content', models.TextField(verbose_name='内容')),
                ('supplier_amount', models.IntegerField(verbose_name='供应商数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
    ]
