# Generated by Django 2.2.4 on 2019-08-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20190817_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linecategory',
            name='product_type',
            field=models.CharField(choices=[('native', '国内'), ('abroad', '国外'), ('surround', '周边'), ('other', '其它'), ('mail_steamer', '邮轮')], max_length=10, verbose_name='产品类型'),
        ),
    ]
