# Generated by Django 2.2.4 on 2019-08-18 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20190818_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='linecategory',
            name='type_en_name',
            field=models.CharField(default=1, max_length=200, verbose_name='英文名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linecategory',
            name='product_type',
            field=models.CharField(choices=[('native', '国内'), ('abroad', '出境'), ('surround', '周边'), ('other', '其它'), ('mail_steamer', '邮轮')], max_length=10, verbose_name='产品类型'),
        ),
    ]
