# Generated by Django 2.2.4 on 2019-08-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20190818_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseline',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='产品名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseline',
            name='product_code',
            field=models.CharField(default=1, max_length=50, verbose_name='产品代码'),
            preserve_default=False,
        ),
    ]
