# Generated by Django 2.2.4 on 2019-08-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20190818_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linecategory',
            old_name='add_time',
            new_name='addTime',
        ),
        migrations.RenameField(
            model_name='linecategory',
            old_name='weight',
            new_name='bySort',
        ),
        migrations.RenameField(
            model_name='linecategory',
            old_name='type_name',
            new_name='cnName',
        ),
        migrations.RenameField(
            model_name='linecategory',
            old_name='type_en_name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='linecategory',
            old_name='supplier_amount',
            new_name='cpyLineNum',
        ),
        migrations.RenameField(
            model_name='linecategory',
            old_name='content',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='linecategory',
            old_name='status',
            new_name='isLock',
        ),
        migrations.RenameField(
            model_name='linecategory',
            old_name='type_account',
            new_name='lineNum',
        ),
        migrations.RenameField(
            model_name='linecategory',
            old_name='deduction_point',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='linecategory',
            old_name='tag_info',
            new_name='tags',
        ),
    ]
