# Generated by Django 2.2.4 on 2019-08-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_auto_20190823_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linecategory',
            old_name='product_type',
            new_name='lineType',
        ),
    ]
